### ISSUE TITLE
Issue on the standard error for the BLUP

### ISSUE THREAD

**Issue by harimurti-buntaran** [covaruber/sommer#10]
Dear Giovanny,

I have a question regarding the standard error of BLUPs produced by Sommer. I am attaching a html file made by Rmarkdown.
 
I tried to analyse a sample data from agridat package (`omer.sorghum`). An MET data with 18 genotypes, 6 environments, with 4 blocks per environment.

The fixed effect is environment.
The random effects are gen, gen:env, and rep within each environment, which employs diagonal vs or rep:at(env).
The residual variances are heterogeneous environment-specific.
 
I found that the standard error of BLUPs from Sommer were larger than those from ASReml-R.
I remember in the previous version you have `RtermsToForce` in the `predict.mmer` function. However, in the version 4.1.1, this statement is not available anymore.
 
The BLUPs are identical to ASReml-R BLUPs.
 
I also checked the RE.used in the predict function, it might be a term is not necessary to be used (env).

I thank you for your attention and help.
 
Best regards,
Harimurti
[Standard-errors-of-BLUPs-Sommer-vs-ASReml-R.docx](https://github.com/covaruber/sommer/files/5516051/Standard-errors-of-BLUPs-Sommer-vs-ASReml-R.docx)

**Comment by covaruber** [comment]
Dear Harimurti, I think I answered this by email but just in case I missed something, Now the way the predict function to force or ignore certain terms in the hypertable is to use the "hypertable" argument and changing the terms that should be included or ignored when building the predictions and standard errors. Also I think the sommer and ASReml SEs are quite similar. Let me know if you find further issues. I will close this issue.

Cheers,
Eduardo
