### ISSUE TITLE
object 'ref.alt' not found

### ISSUE THREAD

**Issue by jeremysutherland** [covaruber/sommer#12]
G1[1:5,1:5]
             Marker_1 Marker_2 Marker_3 Marker_4 Marker_5
Blackwell.01        C        C        A        A        T
Blackwell.02        C        C        A        A        T
Blackwell.03        C        C        A        A        T
Blackwell.04        C        C        A        A        T
Blackwell.05        C        C        A        A        T

G1.num <- atcg1234(G1, ploidy=2, format="ATCG", maf=0.05)
Obtaining reference alleles
  |==========================================================            |  83%Error in FUN(...) : object 'ref.alt' not found

**Comment by covaruber** [comment]
Can you provide the data to replicate the error and correct any possible bug?

Cheers,
Eduardo

**Comment by jeremysutherland** [comment]
Resolved. Error in dataset
________________________________

**Comment by covaruber** [comment]
Sounds good. Have a great day!

Cheers,
Eduardo
