### ISSUE TITLE
the imputed marker matrix is $X, not$imputed

### ISSUE THREAD

**Issue by luansheng** [covaruber/sommer#14]
For A.mat() in the help document:
If return.imputed = TRUE, the function returns a list containing
$A
the A matrix

$imputed
the imputed marker matrix

However, the returned matrix is $X, not $imputed.

**Comment by covaruber** [comment]
Thanks for reporting the bug, we just past the A.mat, D.mat, E.mat and H.mat functions to C++ which caused some of these typos in the documentation. I will address and push in the newest version.

Cheers,
Eduardo
