### ISSUE TITLE
Lack of output in scores

### ISSUE THREAD

**Issue by alakamp** [covaruber/sommer#15]
When I run the model, everything seems to run fine. When I look at the output, the model convergence statement is TRUE. The issue is when I open scores, there are only the SNP names and marker effects. No statistical information is given. A sample of the code and data can be provided directly.

**Comment by alakamp** [comment]
The second column are the -log10 P-values.

**Comment by covaruber** [comment]
Sorry I didn't see this issue before, thanks for putting the answer and closing the issue.

Cheers,
Eduardo
