### ISSUE TITLE
unsBLUP() function

### ISSUE THREAD

**Issue by ntilhou** [covaruber/sommer#17]
Hello,

Is the unsBLUP function supposed to be functional?  I saw it in the GxE information and it would be very convenient if that function was working.

Thanks!
Neal

**Comment by covaruber** [comment]
The intention when that function was created was to be able to predict adjusted means for unstructured models. Now that the predict function works well I thought might not be necessary. Could you explain under which other scenario would be helpful. In that case I can add it again.

Cheers,

**Comment by ntilhou** [comment]
Thank you for the quick reply.  I had not been using the predict function, so I suppose I don't need the unsBLUP function.  The predict function works great for my situation.

Thanks!
Neal
