### ISSUE TITLE
matching (co)variance estimates and standard errors

### ISSUE THREAD

**Issue by LovellHAGSC** [covaruber/sommer#2]
Thanks for your work on the sommer package. 
This is a suggestion / question:

I am trying to estimate the genetic correlation among multiple phenotypes in mmer. This is no problem, via `cov2cor(mmer.model$sigma[["u:id"]])`. I am also trying to get the standard error of sigma, which is stored in `mmer.model$sigmaSE`. However, this returns a matrix that is not of the same dimension as the `mmer.model$sigma` list. 

My questions is, how can I extract the correct standard errors for each element in the covariance matrix?
Thanks, 
John

For example:
```
data("DT_cpdata")
A <- A.mat(GT)
ans.m <- mmer(cbind(Yield,color)~1,
              random=~ vs(id, Gu=A)
              + vs(Rowf,Gtc=diag(2))
              + vs(Colf,Gtc=diag(2)),
              rcov=~ vs(units),
              data=DT)

ans.m$sigma

ans.m$sigmaSE
```
which gives the following output pasted below. 

![image](https://user-images.githubusercontent.com/36449773/52975737-dd6ab100-3383-11e9-8e69-5167e46ec79e.png)

**Comment by covaruber** [comment]
Dear John sorry for the late response, I do not check GitHub that often but I will do. This is great feedback. Indeed it can be confusing to know the correspondence between the sigma object and the the sigmaSE. I have addressed the in the newest version available here in Github, now there's an element called sigmaVector. Thanks again for the good feedback.

**Comment by covaruber** [comment]
I have put column and row names to the matrix sigmaSE of standard errors for variance components and also to the new element called sigmaVector, I hope this helps. This is currently only in the GitHub version.

cheers,
Eduardo
