### ISSUE TITLE
scores in result of GWAS is incomplete

### ISSUE THREAD

**Issue by Mghanbari43** [covaruber/sommer#26]
GWAS function returns only scores (P values), while according to the function vignette, a data frame with 5 columns should be returned.

**Comment by covaruber** [comment]
Dear @Mghanbari43, you're right. I am aware of this issue but the output was changed when I coded the GWAS function in C++, I still have to bring the rest of the output back. Is in my to do list no worries.

**Comment by covaruber** [comment]
I apologize but this will not be longer pursued. GWAS by GBLUP has been replacing the need for the existence of the GWAS function. The GWAS function may be even removed in the future but no longer will be developed further. Take care.

Cheers,
Eduardo
