### ISSUE TITLE
bug in vpredict

### ISSUE THREAD

**Issue by johannesgeibel** [covaruber/sommer#29]
Hi,
there seems to be a bug in vpredict that prevents the output of class "vpredict.mmer" to behave like a data.frame. If you consider to change this code at the end:
```
toreturn2 <- data.frame(row.names = tname, Estimate = tvalue, SE = se)
class(toreturn2) <- "vpredict.mmer"
```
to:
```
toreturn2 <- data.frame(Estimate = tvalue, SE = se)
rownames(toreturn2 ) <- tname # seemed not to be evaluated correctly before in all cases
class(toreturn2) <- c("vpredict.mmer","data.frame") # allows data.frame inheritance

```
all data.frame methods should work, too and handling will be eased

Regards,
Johannes

**Comment by covaruber** [comment]
Thanks for noticing this Johannes. I have added your lines of code and I will push it in the next minutes :)
