### ISSUE TITLE
Suppress "fixed-effect model matrix is rank deficient so dropping 1 columns / coefficients"

### ISSUE THREAD

**Issue by SchmidtPaul** [covaruber/sommer#36]
Hi!
I would like to suppress the "fixed-effect model matrix is rank deficient so dropping 1 columns / coefficients" note, but neither `suppressMessages()` nor `suppressWarnings()` will do the job. Oh yeah and `verbose = FALSE` is also not affecting this. I guess [this line](https://github.com/covaruber/sommer/blob/af358ed5a4e8886dda5ccf7ad026f1187e47bee0/R/mmer.R#L306) could be made an actual warning or if left a cat(...), it could be wrapped in another if-clause adding another argument to silence it?

**Comment by covaruber** [comment]
Thanks for the suggestion Paul, I will address this before I push the new version to CRAN this week. 

Cheers,
Eduardo

**Comment by covaruber** [comment]
Addressed Paul, the version has been submitted now.

Cheers,
Eduardo
