### ISSUE TITLE
Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) :    contrasts can be applied only to factors with 2 or more levels

### ISSUE THREAD

**Issue by MooreZhu** [covaruber/sommer#37]
how to solve this problem

**Comment by covaruber** [comment]
Can you provide a minimal example to recreate the error and find a solution?

Cheers,
Eduardo

**Comment by covaruber** [comment]
Closing since there was no follow up from your side.

Cheers,
Eduardo
