### ISSUE TITLE
GWAS without P3D exits with error

### ISSUE THREAD

**Issue by amkusmec** [covaruber/sommer#4]
As the title says, attempting GWAS with exact tests for every SNP does not run to completion. I've tracked this down to lines 227-231 of `GWAS.R` where the final results are appended to the `lastmodel` object before it is returned from the function. However, if `P3D` is FALSE, the conditional block on lines 94-100 is never executed and `lastmodel` is never created in the scope of the original function, only the scope of `scorecalc()` as each marker is evaluated.

**Comment by covaruber** [comment]
Thanks for the feedback Aaron. I will address this asap and make the fix available in GitHub. I will update the ticket when done. Thanks!

**Comment by covaruber** [comment]
I think this was fixed already. Thanks!
