### ISSUE TITLE
Facing error at the stage of A.mat

### ISSUE THREAD

**Issue by InfiniteLaugh** [covaruber/sommer#40]
Hello! Thanks for developing this excellent program! 
When I try to construct an additive relationship matrix using A.mat, I encountered error issues. The genotype data originated from a .vcf which was converted into .raw data form using plink and performed with protocols as below:

```
m012= fread("plink.raw")
g012 = m012[,-c(3:6)]
dim(g012)
fid = g012$FID
iid = g012$IID
library(sommer)

setDF(g012)
rownames(g012) = g012$IID
g012$IID = NULL
g012$FID = NULL
Gmat = A.mat(g012-1)
```

plink.raw:
![image](https://user-images.githubusercontent.com/62791785/167301652-e4669f6e-c5ac-40a8-bbe8-0bb52886b6b6.png)

However, the program reported error like this:

**Imputing markers with mean value
Error in A.mat(g012 - 1) :
  Not compatible with requested type: [type=list; target=double].**

So I am wondering whether it is the "NA"  in my data, so I replace all "NA" with 0. 
However, nothing changes, what's more, the report "Imputing markers with mean value" was missing if I replace NA.

I don't know what I should do now, could you please give me some suggestions?

Thanks!!

**Comment by covaruber** [comment]
I would need a minimal example to give you an exact answer but I had the feeling that:

```
g012 = m012[,-c(1:6)] # get rid of all columns that are not markers
M = (g012*2) - 1
A = A.mat(M)
```

should do the work. If this doesn't work please provide a minimal example.

Cheers,

**Comment by InfiniteLaugh** [comment]
> I would need a minimal example to give you an exact answer but I had the feeling that:
> 
> ```
> g012 = m012[,-c(1:6)] # get rid of all columns that are not markers
> M = (g012*2) - 1 # I only see 0s and 1s so assume you have to first recode to 0 and 2 and then substract -1
> A = A.mat(M)
> ```
> 
> should do the work. If this doesn't work please provide a minimal example.
> 
> Cheers,

Thank you for your reply, sorry that I was a newcomer to Github, and I am not so sure how to unload data, can you offer me any approach?

**Comment by InfiniteLaugh** [comment]
> I would need a minimal example to give you an exact answer but I had the feeling that:
> 
> ```
> g012 = m012[,-c(1:6)] # get rid of all columns that are not markers
> M = (g012*2) - 1 # I only see 0s and 1s so assume you have to first recode to 0 and 2 and then substract -1
> A = A.mat(M)
> ```
> 
> should do the work. If this doesn't work please provide a minimal example.
> 
> Cheers,

Thank you for your patient reply! Here is the minimal example:
test.vcf.txt was the original data I used to produce plink.raw.txt. plink.raw.txt is the plink.raw I mentioned above.


[test.vcf.txt](https://github.com/covaruber/sommer/files/8666603/test.vcf.txt)
[plink.raw.txt](https://github.com/covaruber/sommer/files/8666602/plink.raw.txt)

Thanks again for your time!

**Comment by covaruber** [comment]
Next time please read the documentation. The function expects a matrix and you provide a data frame.

`Gmat = A.mat(as.matrix(g012)-1)`
