### ISSUE TITLE
Poisson and Negative Bionomial Distributed Traits

### ISSUE THREAD

**Issue by jeremysutherland** [covaruber/sommer#44]
Are there any plans to incorporate other distributions (i.e. poisson or neg. binomial) into mmer's function? 

Perhaps, similar to https://github.com/glmmTMB/glmmTMB?

**Comment by covaruber** [comment]
Dear Jeremy we're waiting for some expert on generalized mixed models to implement this :) I am not good enough on how the reml optimization works in GLMMs. If you have the know-how and can support on it I'll be supper happy to work with you :) but yes, I hope will be there one day.

Cheers,
Eduardo

**Comment by covaruber** [comment]
Closing this enhancement since is the same suggestion than #31 

Thanks.
