### ISSUE TITLE
Throw error for singular system

### ISSUE THREAD

**Issue by BartJanvanRossum** [covaruber/sommer#46]
Using sommer I sometimes get this message. 
```r 
System is singular (V). Stopping the job. Try a bigger number of tolparinv.
``` 
It would be really helpful if this was not just a message, but an actual error. That would make it easier to capture it and handle it properly in e.g a function or a loop.

If you want I could create a pull request for this

**Comment by covaruber** [comment]
Dear Bart, sorry for that. Is a good idea. I will incorporate your suggestion as soon as I work on the new version. Thanks for the suggestion.

Cheers,
Eduardo

**Comment by covaruber** [comment]
Hello Bert, finally working on the issues. Not sure how to achieve this since the message comes from the Rcpp code. The only way I found to capture this error was with 

```
 if(tXVXVX.n_rows == 0){ // finally stop
            Rcpp::Rcout << "System is singular (tXVXVX). Aborting the job. Try a bigger number of tolparinv." << arma::endl;
            return 0;
          }
```
To stop the call when inversion was not possible. How would you propose to do it to return an error instead?

Cheers,
Eduardo

**Comment by BartJanvanRossum** [comment]
Hello Eduardo,
I think in Rcpp you can just use 

```
stop("System is singular (tXVXVX). Aborting the job. Try a bigger number of tolparinv.")
```
See also here (https://teuder.github.io/rcpp4everyone_en/260_error.html)

Cheers,
Bart-Jan

**Comment by covaruber** [comment]
Great Bart, let me put it there now and try it. Thanks 🙂 I hope you're doing well.

Cheers,


G. Eduardo Covarrubias-Pazaran

Quantitative Geneticist / Biometrician

Mobile: +52 595 125 5905

Skype user: cova_ruber

Professional email:

***@***.***

________________________________
De: Bart-Jan van Rossum ***@***.***>
Enviado: domingo, 8 de enero de 2023 12:55 p. m.
Para: covaruber/sommer ***@***.***>
CC: Gio Covarrubias ***@***.***>; Comment ***@***.***>
Asunto: Re: [covaruber/sommer] Throw error for singular system (Issue #46)


Hello Eduardo,
I think in Rcpp you can just use

stop("System is singular (tXVXVX). Aborting the job. Try a bigger number of tolparinv.")


See also here (https://teuder.github.io/rcpp4everyone_en/260_error.html)

Cheers,
Bart-Jan

**Comment by covaruber** [comment]
Done and tested! pushed to GitHub.

Cheers,
Eduardo

**Comment by BartJanvanRossum** [comment]
Nice, thanks for changing this
