### ISSUE TITLE
fitted values from mmer - fixed effects only

### ISSUE THREAD

**Issue by jpiaskowski** [covaruber/sommer#5]
Hello,

I noticed that when `mmer()` calculates the fitted values, it only does so for the fitted effects, but not random effects (even when using type = "complete" like the documentation indicates). This is different from how other mixed model packages treated the `fitted()` function (nlme, lme4, asreml) and other common R classes derived from linear models (lm, glm). Is there a way to extract the predictions from the model object across fixed and random variables? If there is another way to extract this, please let me know. Perhaps I am missing something? From looking at your code, it looks like the `fitted()` function has gone through a few modifications.

Great package, thanks for your work.

**Comment by covaruber** [comment]
Hello Julia, indeed now fitted only provide y=Xb different than before. Currently the best way to obtain the fitted values using all the random effects (Xb+Zu) is to use the predict() function available in sommer. See for example:

```
data(DT_cornhybrids)
DT_cornhybrids <- DT

hybrid2 <- DT # extract cross data
A <- GT
K1 <- A[levels(hybrid2$GCA1), levels(hybrid2$GCA1)]; dim(K1)
K2 <- A[levels(hybrid2$GCA2), levels(hybrid2$GCA2)]; dim(K2)
S <- kronecker(K1, K2) ; dim(S)
rownames(S) <- colnames(S) <- levels(hybrid2$SCA)

ans <- mmer(Yield ~ Location,
             random = ~ vs(GCA1,Gu=K1) + vs(GCA2,Gu=K2) + vs(SCA,Gu=S),
             rcov=~units,
             data=hybrid2)
pp <- predict(ans)
head(pp$fitted) # has all fixed and random effects added
```

I hope this helps. Cheers!

**Comment by jpiaskowski** [comment]
Thank you, will do.
