### ISSUE TITLE
Possible mix up between VanRaden and Endleman GRMs

### ISSUE THREAD

**Issue by timothymillar** [covaruber/sommer#51]
Hi there, thanks for sommer.

I was comparing implementations of the VanRaden GRM estimator across several packages, and I noticed that the the `A.mat` function in sommer seems to produce different values. On further inspection, `A.mat` seems to produce the VanRaden estimate when `endelman=TRUE` and not when `endelman=FALSE`.

Looking at the source code, I think the estimators may have been mixed up as [this](https://github.com/covaruber/sommer/blob/master/src/MNR.cpp#L261) looks to be calculating the VanRaden estimator (note the use of population frequencies) and [this](https://github.com/covaruber/sommer/blob/master/src/MNR.cpp#L274) looks more like the Endelman estimator (note scaling via the mean of diagonal values).

**Comment by covaruber** [comment]
Thanks for the report Timothy. Indeed is a bug. I have pushed some seconds ago to GitHub the new A.mat which only computes the VanRaden method while I figure out the issue in Endelman's method. Indeed the endelman=TRUE was the actual vanRanden. Thanks for reporting this bug. This should also be available on CRAN in the next version.

Cheers,
Eduardo
