### ISSUE TITLE
Cooks distance

### ISSUE THREAD

**Issue by GregorDall** [covaruber/sommer#52]
Dear Eduardo,

do you think it would be feasible to implement a convenience function for the cooks distance value, as is available for lm and lmer? 

Cheers Gregor

**Comment by covaruber** [comment]
Hi Gregor, thanks for the suggestion. If I understand well the literature that would require calculating as many mixed models as observations in the dataset. In many cases that would imply fitting hundreds of thousands of models for a dataset which seems like a very bad idea. I can enable it but I will definitely not recommend it in the documentation haha. I will work on it when I have some spare time this week and drop you a message when it is ready :)

Cheers,
Eduardo
