### ISSUE TITLE
Factor analytic covariance structure updates during REML

### ISSUE THREAD

**Issue by jeffersonfparil** [covaruber/sommer#59]
Hi Giovanny,
Awesome work on this package! Do you have plans on implementing the factor analytic model similar to `ASReml` where the loadings are updated during REML estimation? If so, I would be happy to contribute.
Cheers!

**Comment by covaruber** [comment]
Yes, that was the original intention but I couldn't find in the literature how exactly they do that. Do they produce fitted values at every iteration and calculate new loadings using the fitted values? or do they use the BLUPs? Most sommer machinery is based on the papers from Van der Werf, Karin Meyer, or Jensen. The papers from the ASREML team are too difficult to understand, like leaving gaps intentionally for people to don't recreate their machinery. Long story short, not actively working on the package now but yes, I plan to put that approach at some point. Any clues or suggestion of paper that does a decent job is always welcome.
