### ISSUE TITLE
Factor/character vectors when defining random effect matrices

### ISSUE THREAD

**Issue by amkusmec** [covaruber/sommer#6]
`vs()` has undocumented behavior on line 469 of `FUN_special.R`. I noticed this when my attempt to do genomic prediction only returned random effects for my training set. By contrast, the example in the documentation produced the expected output. This has to do with differences in how `model.matrix()` handles character vs. factor vectors.

If `dummy` is a factor, then while it only contains entries for records with complete data, it also contains the full levels information for the unfiltered data (`dataor` in `mmer()`). `model.matrix()` retains the levels to produce a design matrix with the appropriate number of columns for estimating random effects of records with missing phenotypes. If `dummy` is a character vector, then `model.matrix()` does not have the levels and produces a design matrix for only the training set.

This is easily fixed on the user side by making sure that all categorical variables have the factor type. It would be easiest to highlight this in the documentation for `mmer()` (and perhaps `vs()` as well) so that users don't get confused. Because the documentation for `mmer()` is already quite complex, I think the best solution would be to check silently for character vectors and convert them to factors internally.

**Comment by covaruber** [comment]
Thanks for the feedback Aaron, I will improve the documentation to make users aware but I would prefer to don't mess up with users data and trust they know their data. I remember complaining with Brian Cullis about asreml doing the same haha. I will just put a warning in the vignettes and documentation of mmer() and vs(). Thanks for keep providing this type of feedback Aaron. Have an excellent day!

**Comment by covaruber** [comment]
I decided to apply that silence change suggested by you because I got 2 emails asking the same thing so I hope this doesn't mess up any scenario where that is not desired :) 

Cheers,
Eduardo
