### ISSUE TITLE
could get standard errors for the random effects?

### ISSUE THREAD

**Issue by yzhlinscau** [covaruber/sommer#7]
> rf.sm<-randef(sp.sm)
> names(rf.sm)
[1] "u:Tree"    "Fam"       "u:Row:Col"
> rf.sm$`Fam`$`dbh10`[1:5]
    FamF11     FamF12     FamF13     FamF14     FamF18 
0.10463989 0.34510480 0.04833183 0.28591631 0.24046773

from up codes, it did not show the standard errors for the random effects. Is it possible to get them? If OK, how to do?
Thanks.

Best regards
Yuanzhen Lin

**Comment by covaruber** [comment]
The standard error of a blue is the square root of the diagonal part of the predicted error variance (PEV) matrix:

```
data(DT_cpdata)
DT <- DT_cpdata
GT <- GT_cpdata
MP <- MP_cpdata
### mimic two fields
A <- A.mat(GT)
mix <- mmer(Yield~1,
            random=~vs(id, Gu=A) +
              vs(Rowf) +
              vs(Colf) +
              vs(spl2D(Row,Col)),
            rcov=~vs(units),
            data=DT)
summary(mix)

SE <- sqrt(diag(mix$PevU$`u:id`$Yield))
res <- data.frame(blup=mix$U$`u:id`$Yield + mix$Beta$Estimate,blup_se=SE)
head(res)
```

I hope this helps.

Cheers,
Eduardo
