### ISSUE TITLE
Spl2D gives strange number of effects in spatial analysis

### ISSUE THREAD

**Issue by nickmorales** [covaruber/sommer#8]
In the spatial analysis examples on page 19 and 20 here https://cran.r-project.org/web/packages/sommer/vignettes/sommer.start.pdf why are there 168 rowXcol effects? If the are 13 rows and 36 columns shouldnt there be 468 effects? How can I find the rowXcol effects or is there a different interpretation?
Thank you

**Comment by nickmorales** [comment]
@covaruber am i misinterpretting the example? Is there a way to extract the rowXcol 2dspl effects e.g. 468 effects in that example?

**Comment by covaruber** [comment]
Those are the BLUPs for the spatial effect. The number of terms in the BLUPs element do not need to coincide with the multiplication of row by columns, it depends in the number of knots and degree of the spline used.

`data(DT_cpdata)
DT <- DT_cpdata
GT <- GT_cpdata
MP <- MP_cpdata
### mimic two fields
A <- A.mat(GT)
mix <- mmer(Yield~1,
            random=~vs(id, Gu=A) +
              vs(Rowf) +
              vs(Colf) +
              vs(spl2D(Row,Col)),
            rcov=~vs(units),
            data=DT)
summary(mix)
# make a plot to observe the spatial effects found by the spl2D()
W <- with(DT,spl2D(Row,Col)) # 2D spline incidence matrix
DT$spatial <- W%*%mix$U$`u:Row`$Yield # 2D spline BLUPs
lattice::levelplot(spatial~Row*Col, data=DT) # plot the spatial effect by row and column`

I hope this helps.

Cheers,
Eduardo
